### PR TITLE
Add continuous integrated testing using Travis CI and PlatformIO

### PR DESCRIPTION
**Pull request by photodude**
Add continuous integrated testing using [Travis CI](https://travis-ci.org) and [PlatformIO](https://github.com/platformio/platformio). Requires signing up for the free service [details can be found in the docs](https://docs.travis-ci.com/)

This is a low-level continuous integrated testing the ensures the library functions and PR's are valid.
The low-level Testing verifies the library against the supplied example demo.ino

You can see the passing build with this link to my Travis CI branch which has been configured to test https://travis-ci.org/photodude/DualVNH5019MotorShieldMod3/builds/151091859

Currently, this only tests against 2 boards (uno and megaatmega2560) additional boards can be added for tested. (example with more boards https://travis-ci.org/photodude/DualVNH5019MotorShieldMod3/builds/151090810)

### CODE REVIEW

**Comment by ryantm** [comment]
Cool; thanks for the contribution!

**Comment by photodude** [comment]
You are welcome.

I've got an updated version that breaks the boards out individually and will allow failures for boards that support is in development for (or to just show that the boards don't work). 

If you want I can submit a new PR for that.

**Comment by ryantm** [comment]
Thanks. @DavidEGrayson simplified the .travis.yml file and broke out the boards: https://github.com/pololu/dual-vnh5019-motor-shield/blob/dd13365685a86eed2f75ecd667dd7467e797c298/.travis.yml

**Comment by photodude** [comment]
Those are some nice modifications and simplifications that @DavidEGrayson has made, I have [incorporated those into my .travis.yml](https://github.com/photodude/DualVNH5019MotorShieldMod3/blob/master/.travis.yml) to make my version more portable for adding testing to my other projects.

**Comment by ryantm** [comment]
@photodude I mentioned you in the [blog post](https://www.pololu.com/blog/654/continuous-testing-for-arduino-libraries-using-platformio-and-travis-ci) I wrote about us using this in our Arduino libraries.  By the way, we've updated the [script on master](https://github.com/pololu/dual-vnh5019-motor-shield/blob/master/.travis.yml) to set some shell options so the script properly fails the board compilations fail. Here is an example of the problem: https://travis-ci.org/pololu/balboa-32u4-arduino-library/builds/208827161

**Comment by photodude** [comment]
Thanks for the mention @ryantm glad the contribution was helpful. I'll definitely make that update for my scripts too.

Maybe someday actual unit testing of the arduino libraries can be added.

**Comment by photodude** [comment]
@ryantm one correction on the blog post spelling, my last name is Sorens**e**n. Not a big deal, it's a common difference of e vs o. Again, thanks for the mention in the blog post.

**Comment by ryantm** [comment]
@photodude Sorry! We fixed it!

**Pull request merged**
